services:
  - type: web
    name: sistema-lista-tarefas
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tarefas-db
          property: connectionString

databases:
  - name: tarefas-db
    plan: free
